openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
  description: API for shortening URLs and tracking their usage

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /api/shorten:
    post:
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
              required:
                - url
      responses:
        '200':
          description: URL shortened successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  originalUrl:
                    type: string
                  shortUrl:
                    type: string
                  shortCode:
                    type: string

  /{shortCode}:
    get:
      summary: Redirect to original URL
      parameters:
        - name: shortCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to original URL
        '404':
          description: URL not found

  /api/stats/{shortCode}:
    get:
      summary: Get URL statistics
      parameters:
        - name: shortCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  today:
                    type: integer
                  this_week:
                    type: integer
                  this_month:
                    type: integer